on:
  push:
#    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Install dependencies
#        run: |
#          apt-get update
#          apt-get install -y flatpak-builder

      # https://github.com/marketplace/actions/flatpak-builder
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: tauonmb.flatpak
          manifest-path: com.github.taiko2k.tauonmb.json
          cache-key: flatpak-builder-${{ github.sha }}
